version: '2.3'

services:
  redis:
    image: redis
    expose:
      - 6379

  mysql:
    image: mysql:8.0.19
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: yourapp
      MYSQL_ROOT_PASSWORD: yourapp_password
    volumes:
      - ./application/resources/database/schema_mysql.sql:/docker-entrypoint-initdb.d/schema_mysql.sql
    expose:
      - 3306
    ports:
      - 3306:3306
      - 33060:33060
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    
  yourapp:
    restart: always
    image: yourapp
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./instance:/home/flask/app/instance
      - ./output_files:/home/flask/app/output_files

      - ./application:/home/flask/app/application
      - ./yourapp:/home/flask/app/yourapp
      - web_dist:/home/flask/app/application/veriguide_dashboard_client/build
      - /usr/local/cuda-10.0:/usr/local/cuda-10.0
      - /home/omar/sent:/home/flask/app/yourapp/sent
    runtime: nvidia
    command: /usr/local/bin/gunicorn -w 1 --timeout 600  -b :8001 application:app
    links:
      - redis
    depends_on:
      - redis

  yourapp-worker:
    restart: always
    image: yourapp
    ports:
      - "9001:9001"
    volumes:
      - ./instance:/home/flask/app/instance
      - ./output_files:/home/flask/app/output_files

      - ./application:/home/flask/app/application
      - ./yourapp:/home/flask/app/yourapp

      #- ./log:/tmp
      - ./tika-server.jar:/tmp/tika-server.jar
      - /home/omar/sent:/home/flask/app/yourapp/sent
    runtime: nvidia
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8 
      - FLASK_APP=application
      - WORKER_COUNT=3
      - NVIDIA_VISIBLE_DEVICES=all
    command: /usr/local/bin/supervisord -n -c /home/flask/app/supervisord.conf
    links:
      - redis
    depends_on:
      - redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - '4202:80'
    volumes:
      - web_dist:/www
      - ./css:/www/index/assets-vg/css
    depends_on:
      - yourapp

volumes:
  web_dist:
